apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook
spec:
  selector:
    app: guestbook
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort # Para exponerlo fuera del clúster (e.g. minikube)
  # Opcionalmente, fija un nodePort específico:
  # ports:
  #   - name: http
  #     port: 3000
  #     targetPort: 3000
  #     nodePort: 31000
